module.exports = [
  '**MISC** ,**TEST** ,**Test** ',
  '**TIPS** ,**TIPOUT**,**TIPOUT**',
  '**TIPS** ,**TIPS** ,**TIPS**',
  '**TRANS** ,**TRANS** ,**TRANS**',
  '**MISC** ,ADJUSTMENT,Price Adjust ',
  'ANCILLARY ,AN:BWPHOTO,Black & White Photo Booth',
  'ANCILLARY ,AN:COPHOTO,Color Photo Booth ',
  'ANCILLARY ,AN:GARAGE ,Parking Garage ',
  'ANCILLARY ,AN:HARMO ,Harmonograph ',
  'ANCILLARY ,AN:HURSIM ,Hurricane Simulator ',
  'ANCILLARY ,AN:LOCKER ,Lockers ',
  'ANCILLARY ,AN:PENNY ,Penny Crusher ',
  'ANCILLARY ,AN:PODCAM ,Podcam 360 ',
  'ANCILLARY ,AN:STROLL ,Stroller Rental ',
  'AUDIO ,AUDIO ,Audio Guides ',
  'AV ,AV:EXT ,AV External Items ',
  'AV ,AV:INHOUSE,AV In House Items ',
  'AV ,AV:PKG ,AV Packages ',
  '**MISC** ,BLANKS ,Blanks',
  '**MISC** ,BLASTER ,Blaster Adjustments',
  'CHARGE ,CH:STORE ,PSC Store ',
  'CITYPASS ,CPBOOK ,CityPASS Book ',
  'CITYPASS ,CPVOUCHER ,CityPASS Book Voucher ',
  'DONATION ,DO:ANFUND ,Annual Fund Donation ',
  'EX:SP:PRLV,ES:ADD ,Exhibits Special Add-on ',
  'EX:SP:PRLV,ES:ONLY ,Exhibit Special Only ',
  'EVENTS:21 ,EV2:BREW ,Brewology ',
  'EVENTS:21 ,EV2:HAPPY ,Happy Hour ',
  'EVENTS:21 ,EV2:SPEC ,Spectra ',
  'EVENTS:21 ,EV2:SPIRIT,Science of Spirits ',
  'EVENTS:21 ,EV2:STEM ,STEM: Science Uncorked ',
  'EVENTS:21 ,EV2:SULTRY,Sultry Science ',
  'EVENTS:BD ,EVB:ADDON ,Birthday Party Add-ons ',
  'EVENTS:BD ,EVB:ATT ,Birthday Party Attendance',
  'EVENTS:BD ,EVB:DELUX ,Delux Party ',
  'EVENTS:BD ,EVB:STAN ,Standard Party ',
  'EVENTS:REN,EVR:BLDG ,Building Rental ',
  'EVENTS:REN,EVR:EXTRAS,Event Rental Extras ',
  '**MISC** ,EVR:MISC ,Rental Misc ',
  'EVENTS:REN,EVR:THEAT ,Theater Buyout ',
  'EX:GA ,EX:COMBO ,Exhibit as Combo ',
  'EX:GA ,EX:GSONLY ,Exhibit Only Groups ',
  'EX:GA ,EX:MBONLY ,Exhibit Only Member ',
  'EX:GA ,EX:ONLY ,Exhibit Only ',
  'EX:GA ,EX:ONLYU3 ,Exhibits Only Under 3 ',
  'EX:GA ,EX:SGCOMBO,Exhibit as Combo School ',
  'EX:GA ,EX:SGONLY ,Exhibit Only School ',
  'FB:CON ,FB:COMBO ,Combinations ',
  'FB:IM:BOE ,FBB:BEV ,Beverages ',
  'FB:IM:BOE ,FBB:CANDY ,Candy ',
  'FB:IM:BOE ,FBB:COMBO ,Combinations ',
  'FB:IM:BOE ,FBB:FOOD ,Food ',
  'FB:IM:BOE ,FBB:MISC ,Boeing Concessions Misc ',
  'FB:IM:BOE ,FBB:POPCRN,Popcorn ',
  'FB:IM:BOE ,FBB:SIDES ,Sides ',
  'FB:CAFE ,FBC:BEV ,Beverages ',
  'FB:CAFE ,FBC:CATER ,Catering ',
  'FB:CAFE ,FBC:DESSER,Dessert ',
  'FB:CAFE ,FBC:ENTREE,Entrees ',
  'FB:CAFE ,FBC:FRUVEG,Fruits & Vegetables ',
  'FB:CAFE ,FBC:ICECRE,Ice Cream ',
  'FB:CAFE ,FBC:MISC ,Cafe Misc ',
  'FB:CAFE ,FBC:SALAD ,Salads ',
  'FB:CAFE ,FBC:SIDES ,Sides ',
  'FB:CAFE ,FBC:SNACK ,Snacks ',
  'FB:LS ,FBL:BEV ,Beverages ',
  'FB:LS ,FBL:CANDY ,Candy ',
  'FB:LS ,FBL:MERCH ,Merchandise ',
  'FB:LS ,FBL:SNACK ,Snacks ',
  'FB:IM:PAC ,FBP:BEV ,Beverages ',
  'FB:IM:PAC ,FBP:CANDY ,Candy ',
  'FB:IM:PAC ,FBP:FOOD ,Food ',
  'FB:IM:PAC ,FBP:POPCRN,Popcorn ',
  'FB:BAR ,FBR:BEER ,Beer ',
  'FB:BAR ,FBR:BEV ,Non Alcoholic Beverages ',
  'FB:BAR ,FBR:BLKCSH,Bulk Cash Bar Entry ',
  'FB:BAR ,FBR:LIQUOR,Liqour ',
  'FB:BAR ,FBR:TASTE ,Tastes ',
  'FB:BAR ,FBR:TICKET,Drink Tickets ',
  'FB:BAR ,FBR:WINE ,Wine ',
  'FB:BAR ,FRB:SNACK ,Snacks ',
  'INHSECARDS,GC:CARDS ,Gift Cards ',
  'INHSECARDS,IHC:ACTION,In-House Cards - Actions ',
  'IM:PA:NS ,IM:2DAIRPL,Age of Airplanes 2D ',
  'IM:BO:NS ,IM:2DAIRPL,Age of Airplanes 2D ',
  'IM:BO:ST ,IM:2DCRIM ,Crimson Peak 2D ',
  'IM:BO:ST ,IM:2DHUN4 ,Hunger Games 4 2D ',
  'IM:PA:ST ,IM:2DHUN4 ,Hunger Games 4 2D ',
  'IM:PA:NS ,IM:2DMELON,Watermelon Magic 2D ',
  'IM:BO:ST ,IM:2DMI5 ,Mission Impossible 5 2D ',
  'IM:PA:ST ,IM:2DMI5 ,Mission Impossible 5 2D ',
  'IM:BO:NS ,IM:2DRME ,Rocky Mountain Express 2D',
  'IM:PA:NS ,IM:2DRME ,Rocky Mountain Express 2D',
  'IM:BO:ST ,IM:2DSPEC ,Spectre 2D ',
  'IM:PA:ST ,IM:2DSPEC ,Spectre 2D ',
  'IM:BO:ST ,IM:2DTRAN ,Transporter Refueled 2D ',
  'IM:BO:ST ,IM:2DUNCL ,Man from UNCLE 2D ',
  'IM:BO:ST ,IM:3DANT ,Ant-Man 3D ',
  'IM:BO:ST ,IM:3DEVER ,Everest 3D ',
  '**MISC** ,**TEST** ,**Test** ',
  '**TIPS** ,**TIPOUT**,**TIPOUT**',
  '**TIPS** ,**TIPS** ,**TIPS**',
  '**TRANS** ,**TRANS** ,**TRANS**',
  '**MISC** ,ADJUSTMENT,Price Adjust ',
  'ANCILLARY ,AN:BWPHOTO,Black & White Photo Booth',
  'ANCILLARY ,AN:COPHOTO,Color Photo Booth ',
  'ANCILLARY ,AN:GARAGE ,Parking Garage ',
  'ANCILLARY ,AN:HARMO ,Harmonograph ',
  'ANCILLARY ,AN:HURSIM ,Hurricane Simulator ',
  'ANCILLARY ,AN:LOCKER ,Lockers ',
  'ANCILLARY ,AN:PENNY ,Penny Crusher ',
  'ANCILLARY ,AN:PODCAM ,Podcam 360 ',
  'ANCILLARY ,AN:STROLL ,Stroller Rental ',
  'AUDIO ,AUDIO ,Audio Guides ',
  'AV ,AV:EXT ,AV External Items ',
  'AV ,AV:INHOUSE,AV In House Items ',
  'AV ,AV:PKG ,AV Packages ',
  '**MISC** ,BLANKS ,Blanks',
  '**MISC** ,BLASTER ,Blaster Adjustments',
  'CHARGE ,CH:STORE ,PSC Store ',
  'CITYPASS ,CPBOOK ,CityPASS Book ',
  'CITYPASS ,CPVOUCHER ,CityPASS Book Voucher ',
  'DONATION ,DO:ANFUND ,Annual Fund Donation ',
  'EX:SP:PRLV,ES:ADD ,Exhibits Special Add-on ',
  'EX:SP:PRLV,ES:ONLY ,Exhibit Special Only ',
  'EVENTS:21 ,EV2:BREW ,Brewology ',
  'EVENTS:21 ,EV2:HAPPY ,Happy Hour ',
  'EVENTS:21 ,EV2:SPEC ,Spectra ',
  'EVENTS:21 ,EV2:SPIRIT,Science of Spirits ',
  'EVENTS:21 ,EV2:STEM ,STEM: Science Uncorked ',
  'EVENTS:21 ,EV2:SULTRY,Sultry Science ',
  'EVENTS:BD ,EVB:ADDON ,Birthday Party Add-ons ',
  'EVENTS:BD ,EVB:ATT ,Birthday Party Attendance',
  'EVENTS:BD ,EVB:DELUX ,Delux Party ',
  'EVENTS:BD ,EVB:STAN ,Standard Party ',
  'EVENTS:REN,EVR:BLDG ,Building Rental ',
  'EVENTS:REN,EVR:EXTRAS,Event Rental Extras ',
  '**MISC** ,EVR:MISC ,Rental Misc ',
  'EVENTS:REN,EVR:THEAT ,Theater Buyout ',
  'EX:GA ,EX:COMBO ,Exhibit as Combo ',
  'EX:GA ,EX:GSONLY ,Exhibit Only Groups ',
  'EX:GA ,EX:MBONLY ,Exhibit Only Member ',
  'EX:GA ,EX:ONLY ,Exhibit Only ',
  'EX:GA ,EX:ONLYU3 ,Exhibits Only Under 3 ',
  'EX:GA ,EX:SGCOMBO,Exhibit as Combo School ',
  'EX:GA ,EX:SGONLY ,Exhibit Only School ',
  'FB:CON ,FB:COMBO ,Combinations ',
  'FB:IM:BOE ,FBB:BEV ,Beverages ',
  'FB:IM:BOE ,FBB:CANDY ,Candy ',
  'FB:IM:BOE ,FBB:COMBO ,Combinations ',
  'FB:IM:BOE ,FBB:FOOD ,Food ',
  'FB:IM:BOE ,FBB:MISC ,Boeing Concessions Misc ',
  'FB:IM:BOE ,FBB:POPCRN,Popcorn ',
  'FB:IM:BOE ,FBB:SIDES ,Sides ',
  'FB:CAFE ,FBC:BEV ,Beverages ',
  'FB:CAFE ,FBC:CATER ,Catering ',
  'FB:CAFE ,FBC:DESSER,Dessert ',
  'FB:CAFE ,FBC:ENTREE,Entrees ',
  'FB:CAFE ,FBC:FRUVEG,Fruits & Vegetables ',
  'FB:CAFE ,FBC:ICECRE,Ice Cream ',
  'FB:CAFE ,FBC:MISC ,Cafe Misc ',
  'FB:CAFE ,FBC:SALAD ,Salads ',
  'FB:CAFE ,FBC:SIDES ,Sides ',
  'FB:CAFE ,FBC:SNACK ,Snacks ',
  'FB:LS ,FBL:BEV ,Beverages ',
  'FB:LS ,FBL:CANDY ,Candy ',
  'FB:LS ,FBL:MERCH ,Merchandise ',
  'FB:LS ,FBL:SNACK ,Snacks ',
  'FB:IM:PAC ,FBP:BEV ,Beverages ',
  'FB:IM:PAC ,FBP:CANDY ,Candy ',
  'FB:IM:PAC ,FBP:FOOD ,Food ',
  'FB:IM:PAC ,FBP:POPCRN,Popcorn ',
  'FB:BAR ,FBR:BEER ,Beer ',
  'FB:BAR ,FBR:BEV ,Non Alcoholic Beverages ',
  'FB:BAR ,FBR:BLKCSH,Bulk Cash Bar Entry ',
  'FB:BAR ,FBR:LIQUOR,Liqour ',
  'FB:BAR ,FBR:TASTE ,Tastes ',
  'FB:BAR ,FBR:TICKET,Drink Tickets ',
  'FB:BAR ,FBR:WINE ,Wine ',
  'FB:BAR ,FRB:SNACK ,Snacks ',
  'INHSECARDS,GC:CARDS ,Gift Cards ',
  'INHSECARDS,IHC:ACTION,In-House Cards - Actions ',
  'IM:PA:NS ,IM:2DAIRPL,Age of Airplanes 2D ',
  'IM:BO:NS ,IM:2DAIRPL,Age of Airplanes 2D ',
  'IM:BO:ST ,IM:2DCRIM ,Crimson Peak 2D ',
  'IM:BO:ST ,IM:2DHUN4 ,Hunger Games 4 2D ',
  'IM:PA:ST ,IM:2DHUN4 ,Hunger Games 4 2D ',
  'IM:PA:NS ,IM:2DMELON,Watermelon Magic 2D ',
  'IM:BO:ST ,IM:2DMI5 ,Mission Impossible 5 2D ',
  'IM:PA:ST ,IM:2DMI5 ,Mission Impossible 5 2D ',
  'IM:BO:NS ,IM:2DRME ,Rocky Mountain Express 2D',
  'IM:PA:NS ,IM:2DRME ,Rocky Mountain Express 2D',
  'IM:BO:ST ,IM:2DSPEC ,Spectre 2D ',
  'IM:PA:ST ,IM:2DSPEC ,Spectre 2D ',
  'IM:BO:ST ,IM:2DTRAN ,Transporter Refueled 2D ',
  'IM:BO:ST ,IM:2DUNCL ,Man from UNCLE 2D ',
  'IM:BO:ST ,IM:3DANT ,Ant-Man 3D ',
  'IM:BO:ST ,IM:3DEVER ,Everest 3D ',
  '**MISC** ,**TEST** ,**Test** ',
  '**TIPS** ,**TIPOUT**,**TIPOUT**',
  '**TIPS** ,**TIPS** ,**TIPS**',
  '**TRANS** ,**TRANS** ,**TRANS**',
  '**MISC** ,ADJUSTMENT,Price Adjust ',
  'ANCILLARY ,AN:BWPHOTO,Black & White Photo Booth',
  'ANCILLARY ,AN:COPHOTO,Color Photo Booth ',
  'ANCILLARY ,AN:GARAGE ,Parking Garage ',
  'ANCILLARY ,AN:HARMO ,Harmonograph ',
  'ANCILLARY ,AN:HURSIM ,Hurricane Simulator ',
  'ANCILLARY ,AN:LOCKER ,Lockers ',
  'ANCILLARY ,AN:PENNY ,Penny Crusher ',
  'ANCILLARY ,AN:PODCAM ,Podcam 360 ',
  'ANCILLARY ,AN:STROLL ,Stroller Rental ',
  'AUDIO ,AUDIO ,Audio Guides ',
  'AV ,AV:EXT ,AV External Items ',
  'AV ,AV:INHOUSE,AV In House Items ',
  'AV ,AV:PKG ,AV Packages ',
  '**MISC** ,BLANKS ,Blanks',
  '**MISC** ,BLASTER ,Blaster Adjustments',
  'CHARGE ,CH:STORE ,PSC Store ',
  'CITYPASS ,CPBOOK ,CityPASS Book ',
  'CITYPASS ,CPVOUCHER ,CityPASS Book Voucher ',
  'DONATION ,DO:ANFUND ,Annual Fund Donation ',
  'EX:SP:PRLV,ES:ADD ,Exhibits Special Add-on ',
  'EX:SP:PRLV,ES:ONLY ,Exhibit Special Only ',
  'EVENTS:21 ,EV2:BREW ,Brewology ',
  'EVENTS:21 ,EV2:HAPPY ,Happy Hour ',
  'EVENTS:21 ,EV2:SPEC ,Spectra ',
  'EVENTS:21 ,EV2:SPIRIT,Science of Spirits ',
  'EVENTS:21 ,EV2:STEM ,STEM: Science Uncorked ',
  'EVENTS:21 ,EV2:SULTRY,Sultry Science ',
  'EVENTS:BD ,EVB:ADDON ,Birthday Party Add-ons ',
  'EVENTS:BD ,EVB:ATT ,Birthday Party Attendance',
  'EVENTS:BD ,EVB:DELUX ,Delux Party ',
  'EVENTS:BD ,EVB:STAN ,Standard Party ',
  'EVENTS:REN,EVR:BLDG ,Building Rental ',
  'EVENTS:REN,EVR:EXTRAS,Event Rental Extras ',
  '**MISC** ,EVR:MISC ,Rental Misc ',
  'EVENTS:REN,EVR:THEAT ,Theater Buyout ',
  'EX:GA ,EX:COMBO ,Exhibit as Combo ',
  'EX:GA ,EX:GSONLY ,Exhibit Only Groups ',
  'EX:GA ,EX:MBONLY ,Exhibit Only Member ',
  'EX:GA ,EX:ONLY ,Exhibit Only ',
  'EX:GA ,EX:ONLYU3 ,Exhibits Only Under 3 ',
  'EX:GA ,EX:SGCOMBO,Exhibit as Combo School ',
  'EX:GA ,EX:SGONLY ,Exhibit Only School ',
  'FB:CON ,FB:COMBO ,Combinations ',
  'FB:IM:BOE ,FBB:BEV ,Beverages ',
  'FB:IM:BOE ,FBB:CANDY ,Candy ',
  'FB:IM:BOE ,FBB:COMBO ,Combinations ',
  'FB:IM:BOE ,FBB:FOOD ,Food ',
  'FB:IM:BOE ,FBB:MISC ,Boeing Concessions Misc ',
  'FB:IM:BOE ,FBB:POPCRN,Popcorn ',
  'FB:IM:BOE ,FBB:SIDES ,Sides ',
  'FB:CAFE ,FBC:BEV ,Beverages ',
  'FB:CAFE ,FBC:CATER ,Catering ',
  'FB:CAFE ,FBC:DESSER,Dessert ',
  'FB:CAFE ,FBC:ENTREE,Entrees ',
  'FB:CAFE ,FBC:FRUVEG,Fruits & Vegetables ',
  'FB:CAFE ,FBC:ICECRE,Ice Cream ',
  'FB:CAFE ,FBC:MISC ,Cafe Misc ',
  'FB:CAFE ,FBC:SALAD ,Salads ',
  'FB:CAFE ,FBC:SIDES ,Sides ',
  'FB:CAFE ,FBC:SNACK ,Snacks ',
  'FB:LS ,FBL:BEV ,Beverages ',
  'FB:LS ,FBL:CANDY ,Candy ',
  'FB:LS ,FBL:MERCH ,Merchandise ',
  'FB:LS ,FBL:SNACK ,Snacks ',
  'FB:IM:PAC ,FBP:BEV ,Beverages ',
  'FB:IM:PAC ,FBP:CANDY ,Candy ',
  'FB:IM:PAC ,FBP:FOOD ,Food ',
  'FB:IM:PAC ,FBP:POPCRN,Popcorn ',
  'FB:BAR ,FBR:BEER ,Beer ',
  'FB:BAR ,FBR:BEV ,Non Alcoholic Beverages ',
  'FB:BAR ,FBR:BLKCSH,Bulk Cash Bar Entry ',
  'FB:BAR ,FBR:LIQUOR,Liqour ',
  'FB:BAR ,FBR:TASTE ,Tastes ',
  'FB:BAR ,FBR:TICKET,Drink Tickets ',
  'FB:BAR ,FBR:WINE ,Wine ',
  'FB:BAR ,FRB:SNACK ,Snacks ',
  'INHSECARDS,GC:CARDS ,Gift Cards ',
  'INHSECARDS,IHC:ACTION,In-House Cards - Actions ',
  'IM:PA:NS ,IM:2DAIRPL,Age of Airplanes 2D ',
  'IM:BO:NS ,IM:2DAIRPL,Age of Airplanes 2D ',
  'IM:BO:ST ,IM:2DCRIM ,Crimson Peak 2D ',
  'IM:BO:ST ,IM:2DHUN4 ,Hunger Games 4 2D ',
  'IM:PA:ST ,IM:2DHUN4 ,Hunger Games 4 2D ',
  'IM:PA:NS ,IM:2DMELON,Watermelon Magic 2D ',
  'IM:BO:ST ,IM:2DMI5 ,Mission Impossible 5 2D ',
  'IM:PA:ST ,IM:2DMI5 ,Mission Impossible 5 2D ',
  'IM:BO:NS ,IM:2DRME ,Rocky Mountain Express 2D',
  'IM:PA:NS ,IM:2DRME ,Rocky Mountain Express 2D',
  'IM:BO:ST ,IM:2DSPEC ,Spectre 2D ',
  'IM:PA:ST ,IM:2DSPEC ,Spectre 2D ',
  'IM:BO:ST ,IM:2DTRAN ,Transporter Refueled 2D ',
  'IM:BO:ST ,IM:2DUNCL ,Man from UNCLE 2D ',
  'IM:BO:ST ,IM:3DANT ,Ant-Man 3D ',
  'IM:BO:ST ,IM:3DEVER ,Everest 3D ',
  '**MISC** ,**TEST** ,**Test** ',
  '**TIPS** ,**TIPOUT**,**TIPOUT**',
  '**TIPS** ,**TIPS** ,**TIPS**',
  '**TRANS** ,**TRANS** ,**TRANS**',
  '**MISC** ,ADJUSTMENT,Price Adjust ',
  'ANCILLARY ,AN:BWPHOTO,Black & White Photo Booth',
  'ANCILLARY ,AN:COPHOTO,Color Photo Booth ',
  'ANCILLARY ,AN:GARAGE ,Parking Garage ',
  'ANCILLARY ,AN:HARMO ,Harmonograph ',
  'ANCILLARY ,AN:HURSIM ,Hurricane Simulator ',
  'ANCILLARY ,AN:LOCKER ,Lockers ',
  'ANCILLARY ,AN:PENNY ,Penny Crusher ',
  'ANCILLARY ,AN:PODCAM ,Podcam 360 ',
  'ANCILLARY ,AN:STROLL ,Stroller Rental ',
  'AUDIO ,AUDIO ,Audio Guides ',
  'AV ,AV:EXT ,AV External Items ',
  'AV ,AV:INHOUSE,AV In House Items ',
  'AV ,AV:PKG ,AV Packages ',
  '**MISC** ,BLANKS ,Blanks',
  '**MISC** ,BLASTER ,Blaster Adjustments',
  'CHARGE ,CH:STORE ,PSC Store ',
  'CITYPASS ,CPBOOK ,CityPASS Book ',
  'CITYPASS ,CPVOUCHER ,CityPASS Book Voucher ',
  'DONATION ,DO:ANFUND ,Annual Fund Donation ',
  'EX:SP:PRLV,ES:ADD ,Exhibits Special Add-on ',
  'EX:SP:PRLV,ES:ONLY ,Exhibit Special Only ',
  'EVENTS:21 ,EV2:BREW ,Brewology ',
  'EVENTS:21 ,EV2:HAPPY ,Happy Hour ',
  'EVENTS:21 ,EV2:SPEC ,Spectra ',
  'EVENTS:21 ,EV2:SPIRIT,Science of Spirits ',
  'EVENTS:21 ,EV2:STEM ,STEM: Science Uncorked ',
  'EVENTS:21 ,EV2:SULTRY,Sultry Science ',
  'EVENTS:BD ,EVB:ADDON ,Birthday Party Add-ons ',
  'EVENTS:BD ,EVB:ATT ,Birthday Party Attendance',
  'EVENTS:BD ,EVB:DELUX ,Delux Party ',
  'EVENTS:BD ,EVB:STAN ,Standard Party ',
  'EVENTS:REN,EVR:BLDG ,Building Rental ',
  'EVENTS:REN,EVR:EXTRAS,Event Rental Extras ',
  '**MISC** ,EVR:MISC ,Rental Misc ',
  'EVENTS:REN,EVR:THEAT ,Theater Buyout ',
  'EX:GA ,EX:COMBO ,Exhibit as Combo ',
  'EX:GA ,EX:GSONLY ,Exhibit Only Groups ',
  'EX:GA ,EX:MBONLY ,Exhibit Only Member ',
  'EX:GA ,EX:ONLY ,Exhibit Only ',
  'EX:GA ,EX:ONLYU3 ,Exhibits Only Under 3 ',
  'EX:GA ,EX:SGCOMBO,Exhibit as Combo School ',
  'EX:GA ,EX:SGONLY ,Exhibit Only School ',
  'FB:CON ,FB:COMBO ,Combinations ',
  'FB:IM:BOE ,FBB:BEV ,Beverages ',
  'FB:IM:BOE ,FBB:CANDY ,Candy ',
  'FB:IM:BOE ,FBB:COMBO ,Combinations ',
  'FB:IM:BOE ,FBB:FOOD ,Food ',
  'FB:IM:BOE ,FBB:MISC ,Boeing Concessions Misc ',
  'FB:IM:BOE ,FBB:POPCRN,Popcorn ',
  'FB:IM:BOE ,FBB:SIDES ,Sides ',
  'FB:CAFE ,FBC:BEV ,Beverages ',
  'FB:CAFE ,FBC:CATER ,Catering ',
  'FB:CAFE ,FBC:DESSER,Dessert ',
  'FB:CAFE ,FBC:ENTREE,Entrees ',
  'FB:CAFE ,FBC:FRUVEG,Fruits & Vegetables ',
  'FB:CAFE ,FBC:ICECRE,Ice Cream ',
  'FB:CAFE ,FBC:MISC ,Cafe Misc ',
  'FB:CAFE ,FBC:SALAD ,Salads ',
  'FB:CAFE ,FBC:SIDES ,Sides ',
  'FB:CAFE ,FBC:SNACK ,Snacks ',
  'FB:LS ,FBL:BEV ,Beverages ',
  'FB:LS ,FBL:CANDY ,Candy ',
  'FB:LS ,FBL:MERCH ,Merchandise ',
  'FB:LS ,FBL:SNACK ,Snacks ',
  'FB:IM:PAC ,FBP:BEV ,Beverages ',
  'FB:IM:PAC ,FBP:CANDY ,Candy ',
  'FB:IM:PAC ,FBP:FOOD ,Food ',
  'FB:IM:PAC ,FBP:POPCRN,Popcorn ',
  'FB:BAR ,FBR:BEER ,Beer ',
  'FB:BAR ,FBR:BEV ,Non Alcoholic Beverages ',
  'FB:BAR ,FBR:BLKCSH,Bulk Cash Bar Entry ',
  'FB:BAR ,FBR:LIQUOR,Liqour ',
  'FB:BAR ,FBR:TASTE ,Tastes ',
  'FB:BAR ,FBR:TICKET,Drink Tickets ',
  'FB:BAR ,FBR:WINE ,Wine ',
  'FB:BAR ,FRB:SNACK ,Snacks ',
  'INHSECARDS,GC:CARDS ,Gift Cards ',
  'INHSECARDS,IHC:ACTION,In-House Cards - Actions ',
  'IM:PA:NS ,IM:2DAIRPL,Age of Airplanes 2D ',
  'IM:BO:NS ,IM:2DAIRPL,Age of Airplanes 2D ',
  'IM:BO:ST ,IM:2DCRIM ,Crimson Peak 2D ',
  'IM:BO:ST ,IM:2DHUN4 ,Hunger Games 4 2D ',
  'IM:PA:ST ,IM:2DHUN4 ,Hunger Games 4 2D ',
  'IM:PA:NS ,IM:2DMELON,Watermelon Magic 2D ',
  'IM:BO:ST ,IM:2DMI5 ,Mission Impossible 5 2D ',
  'IM:PA:ST ,IM:2DMI5 ,Mission Impossible 5 2D ',
  'IM:BO:NS ,IM:2DRME ,Rocky Mountain Express 2D',
  'IM:PA:NS ,IM:2DRME ,Rocky Mountain Express 2D',
  'IM:BO:ST ,IM:2DSPEC ,Spectre 2D ',
  'IM:PA:ST ,IM:2DSPEC ,Spectre 2D ',
  'IM:BO:ST ,IM:2DTRAN ,Transporter Refueled 2D ',
  'IM:BO:ST ,IM:2DUNCL ,Man from UNCLE 2D ',
  'IM:BO:ST ,IM:3DANT ,Ant-Man 3D ',
  'IM:BO:ST ,IM:3DEVER ,Everest 3D ',
  '',
];
